In [1]:
import pandas as pd
import os

In [3]:
os.getcwd()

'/Users/yanzhongsu/wanrong/postcode-processing-ONS'

In [ ]:
# Load the main ONS postcode data with GSS codes
df_pc = pd.read_csv("data/raw/ONSPD_AUG_2025_UK.csv")

/var/folders/7g/3p8d_8ss0y1bp_kvxr1rsrbr0000gn/T/ipykernel_32764/1878757309.py:1: DtypeWarning: Columns (0: ssr95cd, 1: ruc01ind, 2: ruc11ind, 3: lep21cd2, 4: ruc21ind) have mixed types. Specify dtype option on import or set low_memory=False.
  df_pc = pd.read_csv("data/raw/ONSPD_AUG_2025_UK.csv")

In [29]:
df_pc.shape

(2717743, 53)

In [ ]:
# Select relevant columns
df_pc = df_pc[["pcds", "ctry25cd", "rgn25cd", "cty25cd", "ruc11ind", "ruc21ind", "lat", "long"]]

In [33]:
df_pc.head()

,pcds,ctry25cd,rgn25cd,cty25cd,ruc11ind,ruc21ind,lat,long
0,AB1 0AA,S92000003,S99999999,S99999999,3.0,1.0,57.101459,-2.242858
1,AB1 0AB,S92000003,S99999999,S99999999,3.0,1.0,57.102539,-2.246315
2,AB1 0AD,S92000003,S99999999,S99999999,3.0,1.0,57.100541,-2.248349
3,AB1 0AE,S92000003,S99999999,S99999999,6.0,5.0,57.084429,-2.255714
4,AB1 0AF,S92000003,S99999999,S99999999,3.0,1.0,57.096641,-2.258109

In [10]:
# load lookup tables
df_country = pd.read_csv('data/raw/CTRY Country names and codes UK as at 05_25.csv', usecols=['CTRY25CD', 'CTRY25NM'])
df_country

    CTRY25CD           CTRY25NM
0  E92000001            England
1  K02000001     United Kingdom
2  K03000001      Great Britain
3  K04000001  England and Wales
4  N92000002   Northern Ireland
5  S92000003           Scotland
6  W92000004              Wales

In [35]:
df_region = pd.read_csv('data/raw/RGN Region names and codes EN as at 05_25.csv', usecols=['RGN25CD', 'RGN25NM'])
df_region

      RGN25CD                   RGN25NM
0   E12000001                North East
1   E12000002                North West
2   E12000003  Yorkshire and The Humber
3   E12000004             East Midlands
4   E12000005             West Midlands
5   E12000006           East of England
6   E12000007                    London
7   E12000008                South East
8   E12000009                South West
9   S99999999                  Scotland
10  W99999999                     Wales
11  N99999999          Northern Ireland

In [36]:
df_county = pd.read_csv('data/raw/CTY County names and codes UK as at 05_25.csv', usecols=['CTY25CD', 'CTY25NM'])
df_county

      CTY25CD                      CTY25NM
0   E10000003               Cambridgeshire
1   E10000007                   Derbyshire
2   E10000008                        Devon
3   E10000011                  East Sussex
4   E10000012                        Essex
5   E10000013              Gloucestershire
6   E10000014                    Hampshire
7   E10000015                Hertfordshire
8   E10000016                         Kent
9   E10000017                   Lancashire
10  E10000018               Leicestershire
11  E10000019                 Lincolnshire
12  E10000020                      Norfolk
13  E10000024              Nottinghamshire
14  E10000025                  Oxfordshire
15  E10000028                Staffordshire
16  E10000029                      Suffolk
17  E10000030                       Surrey
18  E10000031                 Warwickshire
19  E10000032                  West Sussex
20  E10000034               Worcestershire
21  E99999999  (pseudo) England (UA/MD/LB)
22  L99999999     (pseudo) Channel Islands
23  M99999999         (pseudo) Isle of Man
24  N99999999    (pseudo) Northern Ireland
25  S99999999            (pseudo) Scotland
26  W99999999               (pseudo) Wales

In [37]:
df_ruc_ew = pd.read_csv('data/raw/RUC21 Rural Urban (2021) Indicator names and codes EW as at 05_25.csv')
df_ruc_ew

  RUC21IND                                         RUC21DESC Urban_rural_flag
0     RLF1   Larger rural: Further from a major town or city            Rural
1     RLN1      Larger rural: Nearer to a major town or city            Rural
2     RSF1  Smaller rural: Further from a major town or city            Rural
3     RSN1     Smaller rural: Nearer to a major town or city            Rural
4      UF1          Urban: Further from a major town or city            Urban
5      UN1             Urban: Nearer to a major town or city            Urban

In [38]:
df_ruc_sc = pd.read_csv('data/raw/RUC21 Rural Urban (2021) Indicator names and codes SC as at 05_25.csv')
df_ruc_sc

   RUC21IND               RUC21DESC
0         1       Large Urban Areas
1         2       Other Urban Areas
2         3  Accessible Small Towns
3         4      Remote Small Towns
4         5        Accessible Rural
5         6            Remote Rural

In [ ]:
# Add a new column to indicate urban/rural status for Scotland
df_ruc_sc['Urban_rural_flag'] = ['Urban', 'Urban', 'Rural', 'Rural', 'Rural', 'Rural']
df_ruc_sc

   RUC21IND               RUC21DESC Urban_rural_flag
0         1       Large Urban Areas            Urban
1         2       Other Urban Areas            Urban
2         3  Accessible Small Towns            Rural
3         4      Remote Small Towns            Rural
4         5        Accessible Rural            Rural
5         6            Remote Rural            Rural

In [ ]:
 # Combine the England/Wales and Scotland rural/urban classification tables
 df_ruc21 = pd.concat([df_ruc_ew, df_ruc_sc], axis=0, ignore_index=True)
 df_ruc21

   RUC21IND                                         RUC21DESC Urban_rural_flag
0      RLF1   Larger rural: Further from a major town or city            Rural
1      RLN1      Larger rural: Nearer to a major town or city            Rural
2      RSF1  Smaller rural: Further from a major town or city            Rural
3      RSN1     Smaller rural: Nearer to a major town or city            Rural
4       UF1          Urban: Further from a major town or city            Urban
5       UN1             Urban: Nearer to a major town or city            Urban
6         1                                 Large Urban Areas            Urban
7         2                                 Other Urban Areas            Urban
8         3                            Accessible Small Towns            Rural
9         4                                Remote Small Towns            Rural
10        5                                  Accessible Rural            Rural
11        6                                      Remote Rural            Rural

In [41]:
df_pc.head()

,pcds,ctry25cd,rgn25cd,cty25cd,ruc11ind,ruc21ind,lat,long
0,AB1 0AA,S92000003,S99999999,S99999999,3.0,1.0,57.101459,-2.242858
1,AB1 0AB,S92000003,S99999999,S99999999,3.0,1.0,57.102539,-2.246315
2,AB1 0AD,S92000003,S99999999,S99999999,3.0,1.0,57.100541,-2.248349
3,AB1 0AE,S92000003,S99999999,S99999999,6.0,5.0,57.084429,-2.255714
4,AB1 0AF,S92000003,S99999999,S99999999,3.0,1.0,57.096641,-2.258109

In [ ]:
# Merge the lookup tables with the main postcode dataframe
df_pc = df_pc.merge(df_country, left_on='ctry25cd', right_on='CTRY25CD', how='left')
df_pc = df_pc.merge(df_region, left_on='rgn25cd', right_on='RGN25CD', how='left')
df_pc = df_pc.merge(df_county, left_on='cty25cd', right_on='CTY25CD', how='left')
df_pc = df_pc.merge(df_ruc21, left_on='ruc21ind', right_on='RUC21IND', how='left')

In [ ]:
# Select and reorder columns for the final output
df_pc = df_pc[["pcds", "CTRY25NM", "RGN25NM", "CTY25NM", "RUC21DESC", "Urban_rural_flag", "lat", "long"]]
df_pc.head()

,pcds,CTRY25NM,RGN25NM,CTY25NM,RUC21DESC,Urban_rural_flag,lat,long
0,AB1 0AA,Scotland,Scotland,(pseudo) Scotland,Large Urban Areas,Urban,57.101459,-2.242858
1,AB1 0AB,Scotland,Scotland,(pseudo) Scotland,Large Urban Areas,Urban,57.102539,-2.246315
2,AB1 0AD,Scotland,Scotland,(pseudo) Scotland,Large Urban Areas,Urban,57.100541,-2.248349
3,AB1 0AE,Scotland,Scotland,(pseudo) Scotland,Accessible Rural,Rural,57.084429,-2.255714
4,AB1 0AF,Scotland,Scotland,(pseudo) Scotland,Large Urban Areas,Urban,57.096641,-2.258109

In [45]:
df_pc['CTRY25NM'].unique()

<StringArray>
['Scotland', 'England', 'Northern Ireland', 'Wales', nan]
Length: 5, dtype: str

In [46]:
df_pc['RGN25NM'].unique()

<StringArray>
[                'Scotland',          'East of England',
                        nan,            'West Midlands',
            'East Midlands',               'South West',
               'North West', 'Yorkshire and The Humber',
               'South East',                   'London',
         'Northern Ireland',               'North East',
                    'Wales']
Length: 13, dtype: str

In [47]:
df_pc['RUC21DESC'].unique()

<StringArray>
[                               'Large Urban Areas',
                                 'Accessible Rural',
                               'Remote Small Towns',
                           'Accessible Small Towns',
                                'Other Urban Areas',
                                                nan,
                                     'Remote Rural',
            'Urban: Nearer to a major town or city',
    'Smaller rural: Nearer to a major town or city',
     'Larger rural: Nearer to a major town or city',
  'Larger rural: Further from a major town or city',
 'Smaller rural: Further from a major town or city',
         'Urban: Further from a major town or city']
Length: 13, dtype: str

In [48]:
df_pc['Urban_rural_flag'].unique()

<StringArray>
['Urban', 'Rural', nan]
Length: 3, dtype: str

In [55]:
df_pc.groupby('Urban_rural_flag')['RUC21DESC'].unique()

Urban_rural_flag
Rural    [Accessible Rural, Remote Small Towns, Accessi...
Urban    [Large Urban Areas, Other Urban Areas, Urban: ...
Name: RUC21DESC, dtype: object

In [57]:
df_pc.shape

(2717743, 8)

In [ ]:
# Save the processed dataframe to a new CSV file
df_pc.to_csv('data/output/ons_postcode_processed.csv', index=False)

### Use Duckdb

In [1]:
import pandas as pd
import duckdb
import time
start_time = time.time()

In [ ]:
df_pc = duckdb.query("SELECT pcds, ctry25cd, rgn25cd, cty25cd, ruc21ind, lat, long FROM read_csv('data/raw/ONSPD_AUG_2025_UK.csv', types={'ruc21ind': 'VARCHAR'})").to_df()

,pcds,ctry25cd,rgn25cd,cty25cd,ruc21ind,lat,long
0,AB1 0AA,S92000003,S99999999,S99999999,1,57.101459,-2.242858
1,AB1 0AB,S92000003,S99999999,S99999999,1,57.102539,-2.246315
2,AB1 0AD,S92000003,S99999999,S99999999,1,57.100541,-2.248349
3,AB1 0AE,S92000003,S99999999,S99999999,5,57.084429,-2.255714
4,AB1 0AF,S92000003,S99999999,S99999999,1,57.096641,-2.258109
...,...,...,...,...,...,...,...
2717738,ZE3 9JW,S92000003,S99999999,S99999999,6,59.873657,-1.305701
2717739,ZE3 9JX,S92000003,S99999999,S99999999,6,59.875292,-1.307506
2717740,ZE3 9JY,S92000003,S99999999,S99999999,6,59.891578,-1.313851
2717741,ZE3 9JZ,S92000003,S99999999,S99999999,6,59.892398,-1.310904
2717742,ZE3 9XP,S92000003,S99999999,S99999999,6,59.887109,-1.307582

In [14]:
duckdb.query("SELECT CTRY25CD, CTRY25NM FROM read_csv('data/raw/CTRY Country names and codes UK as at 05_25.csv', header=True)").to_df()

    CTRY25CD           CTRY25NM
0  E92000001            England
1  K02000001     United Kingdom
2  K03000001      Great Britain
3  K04000001  England and Wales
4  N92000002   Northern Ireland
5  S92000003           Scotland
6  W92000004              Wales

In [41]:
df_region = duckdb.query("""
SELECT * 
FROM read_csv(
    'data/raw/RGN Region names and codes EN as at 05_25.csv',
    delim=',',
    header=True
    )
""").to_df()
df_region

InvalidInputException: Invalid Input Error: Error when sniffing file "data/raw/RGN Region names and codes EN as at 05_25.csv".
It was not possible to automatically detect the CSV parsing dialect
The search space used was:
Delimiter Candidates: ','
Quote/Escape Candidates: ['(no quote)','(no escape)'],['"','(no escape)'],['"','"'],['"','''],['"','\'],[''','(no escape)'],[''','''],[''','"'],[''','\']
Comment Candidates: '\0', '#'
Encoding: utf-8
Possible fixes:
* Disable the parser's strict mode (strict_mode=false) to allow reading rows that do not comply with the CSV standard.
* Make sure you are using the correct file encoding. If not, set it (e.g., encoding = 'utf-16').
* Delimiter is set to ','. Consider unsetting it.
* Set quote (e.g., quote='"')
* Set escape (e.g., escape='"')
* Set comment (e.g., comment='#')
* Set skip (skip=${n}) to skip ${n} lines at the top of the file
* Enable ignore errors (ignore_errors=true) to ignore potential errors
* Enable null padding (null_padding=true) to pad missing columns with NULL values
* Check you are using the correct file compression, otherwise set it (e.g., compression = 'zstd')
* Be sure that the maximum line size is set to an appropriate value, otherwise set it (e.g., max_line_size=10000000)

In [38]:
with open("data/raw/RGN Region names and codes EN as at 05_25.csv", "r") as f:
    print(f.readline())

RGN25CD,RGN25NM,RGN25NMW

In [36]:
import pandas as pd
df_test = pd.read_csv('data/raw/RGN Region names and codes EN as at 05_25.csv')
df_test.head()

     RGN25CD                   RGN25NM                RGN25NMW
0  E12000001                North East        Gogledd Ddwyrain
1  E12000002                North West        Gogledd Orllewin
2  E12000003  Yorkshire and The Humber    Swydd Efrog a Humber
3  E12000004             East Midlands    Dwyrain y Canolbarth
4  E12000005             West Midlands  Gorllewin y Canolbarth